### ISSUE TITLE
Endpoint/param order preservation

### ISSUE THREAD

**Issue by jankuca** [airtasker/spot#1135]
I've noticed that endpoints, types, headers and params get ordered alphabetically in the resulting OpenAPI. We would rather like to preserve the order instead as it would help improve the readability of an API documentation generated from the OpenAPI file.

I understand that this preference might not be 100% common so instead of pushing the complete removal of sorting, I'm proposing a new flag for the `generate` command which would make the parser preserve the order of various elements:

```
spot generate --preserveOrder …
```

Here is an example of an unexpected output:

```ts
@endpoint({ path: '/designs/:design_id/artboards/:artboard_id' })
class DesignPageEndpoint {
  @request
  request(
    @pathParams
    _pathParams: {
      'design_id': string,
      'artboard_id': string,
    }
  ) {}
}
```
OpenAPI:

```json
  "parameters": [
    {
      "name": "artboard_id",
      "in": "path",
      "required": true,
      "schema": {
        "type": "string"
      }
    },
    {
      "name": "design_id",
      "in": "path",
      "required": true,
      "schema": {
        "type": "string"
      }
    }
  ]
```

(I've actually started working on a PR for this.)

**Comment by lfportal** [comment]
Hi @jankuca many of Spot's components perform sorting currently at the parser level rather than during contract generation. I don't recall there being a strong reason for sorting. Given your proposed example, I think the **sane default should be preserved order**. Rather than introducing a flag, I think it makes more sense to removing sorted results altogether from the parser. If there is desire for sorting, it can later be introduced to the contract generation stage.

**Comment by jankuca** [comment]
Perfect, sounds good to me to remove it completely.

**Comment by jankuca** [comment]
I have updated the PR to just remove the sorting.
